routes/web.php
<?php

//Route::domain(env('APP_URL_BASE'))->group(function() {
//
//    Route::get('login', 'System\LoginController@showLoginForm')->name('login');
//    Route::post('login', 'System\LoginController@login');
//    Route::post('logout', 'System\LoginController@logout')->name('logout');
//
//    Route::middleware('auth:admin')->group(function() {
////        Route::get('/', function () {
////            return view('system.dashboard');
////        });
//        Route::get('dashboard', 'System\HomeController@index')->name('system.dashboard');
//        Route::get('clients', 'System\ClientController@index');
//        Route::get('clients/records', 'System\ClientController@records');
//        Route::get('clients/create', 'System\ClientController@create');
////        Route::resource('clients', 'System\ClientController');
//
//        //Clients
//        Route::get('clients', 'System\ClientController@index')->name('clients.index');
//        Route::get('clients/create', 'System\ClientController@create')->name('clients.create');
//        Route::get('clients/tables', 'System\ClientController@tables');
//        Route::get('clients/record', 'System\ClientController@record');
//        Route::get('clients/records', 'System\ClientController@records');
//        Route::post('clients', 'System\ClientController@store');
//    });
//});

$hostname = app(Hyn\Tenancy\Contracts\CurrentHostname::class);

if ($hostname) {
    Route::domain($hostname->fqdn)->group(function() {

        Auth::routes();

        Route::get('search', 'Tenant\SearchController@index')->name('search.index');
        Route::get('buscar', 'Tenant\SearchController@index')->name('search.index');
        Route::get('search/tables', 'Tenant\SearchController@tables');
        Route::post('search', 'Tenant\SearchController@store');
        Route::get('downloads/document/{type}/{external_id}', 'Tenant\DocumentController@downloadExternal')->name('tenant.documents.download_external');

        Route::middleware('auth')->group(function() {
            Route::get('/', function () {
                return redirect()->route('tenant.documents.create');
            });
            Route::get('dashboard', 'Tenant\HomeController@index')->name('tenant.dashboard');

            //Company
            Route::get('companies/create', 'Tenant\CompanyController@create')->name('tenant.companies.create');
            Route::get('companies/tables', 'Tenant\CompanyController@tables');
            Route::get('companies/record', 'Tenant\CompanyController@record');
            Route::post('companies', 'Tenant\CompanyController@store');
            Route::post('companies/uploads', 'Tenant\CompanyController@uploadFile');

            //Certificates
            Route::get('certificates/record', 'Tenant\CertificateController@record');
            Route::post('certificates/uploads', 'Tenant\CertificateController@uploadFile');
            Route::delete('certificates', 'Tenant\CertificateController@destroy');

            //Establishments
            Route::get('establishments/create', 'Tenant\EstablishmentController@create');
            Route::get('establishments/tables', 'Tenant\EstablishmentController@tables');
            Route::get('establishments/record', 'Tenant\EstablishmentController@record');
            Route::post('establishments', 'Tenant\EstablishmentController@store');

            //Bank Accounts
            Route::get('bank_accounts', 'Tenant\BankAccountController@index')->name('tenant.bank_accounts.index');
            Route::get('bank_accounts/records', 'Tenant\BankAccountController@records');
            Route::get('bank_accounts/create', 'Tenant\BankAccountController@create');
            Route::get('bank_accounts/tables', 'Tenant\BankAccountController@tables');
            Route::get('bank_accounts/record/{bank_account}', 'Tenant\BankAccountController@record');
            Route::post('bank_accounts', 'Tenant\BankAccountController@store');
            Route::delete('bank_accounts/{bank_account}', 'Tenant\BankAccountController@destroy');

            //Series
            Route::get('series/records', 'Tenant\SeriesController@records');
            Route::get('series/create', 'Tenant\SeriesController@create');
            Route::get('series/tables', 'Tenant\SeriesController@tables');
            Route::post('series', 'Tenant\SeriesController@store');
            Route::delete('series/{series}', 'Tenant\SeriesController@destroy');

            //Users
            Route::get('users/create', 'Tenant\UserController@create')->name('tenant.users.create');
            Route::get('users/tables', 'Tenant\UserController@tables');
            Route::get('users/record/{user}', 'Tenant\UserController@record');
            Route::post('users', 'Tenant\UserController@store');
            Route::get('users/records', 'Tenant\UserController@records');
            Route::delete('users/{user}', 'Tenant\UserController@destroy');

            //ChargeDiscounts
            Route::get('charge_discounts', 'Tenant\ChargeDiscountController@index')->name('tenant.charge_discounts.index');
            Route::get('charge_discounts/records/{type}', 'Tenant\ChargeDiscountController@records');
            Route::get('charge_discounts/create', 'Tenant\ChargeDiscountController@create');
            Route::get('charge_discounts/tables/{type}', 'Tenant\ChargeDiscountController@tables');
            Route::get('charge_discounts/record/{charge}', 'Tenant\ChargeDiscountController@record');
            Route::post('charge_discounts', 'Tenant\ChargeDiscountController@store');
            Route::delete('charge_discounts/{charge}', 'Tenant\ChargeDiscountController@destroy');

            //Items
            Route::get('items', 'Tenant\ItemController@index')->name('tenant.items.index');
            Route::get('items/columns', 'Tenant\ItemController@columns');
            Route::get('items/records', 'Tenant\ItemController@records');
            Route::get('items/tables', 'Tenant\ItemController@tables');
            Route::get('items/record/{item}', 'Tenant\ItemController@record');
            Route::post('items', 'Tenant\ItemController@store');
            Route::delete('items/{item}', 'Tenant\ItemController@destroy');

            //Customers
            Route::get('customers', 'Tenant\CustomerController@index')->name('tenant.customers.index');
            Route::get('customers/columns', 'Tenant\CustomerController@columns');
            Route::get('customers/records', 'Tenant\CustomerController@records');
            Route::get('customers/tables', 'Tenant\CustomerController@tables');
            Route::get('customers/record/{item}', 'Tenant\CustomerController@record');
            Route::post('customers', 'Tenant\CustomerController@store');
            Route::delete('customers/{customer}', 'Tenant\CustomerController@destroy');

            //Documents
            Route::get('documents', 'Tenant\DocumentController@index')->name('tenant.documents.index');
            Route::get('documents/columns', 'Tenant\DocumentController@columns');
            Route::get('documents/records', 'Tenant\DocumentController@records');
            Route::get('documents/create', 'Tenant\DocumentController@create')->name('tenant.documents.create');
            Route::get('documents/tables', 'Tenant\DocumentController@tables');
            Route::get('documents/record/{document}', 'Tenant\DocumentController@record');
            Route::post('documents', 'Tenant\DocumentController@store');
            Route::post('documents/voided', 'Tenant\DocumentController@voided');
            Route::get('documents/to_print/{document}', 'Tenant\DocumentController@to_print');
            Route::get('documents/to_print2/{document}/{format}', 'Tenant\DocumentController@to_print2');

            Route::get('documents/download/{type}/{document}', 'Tenant\DocumentController@download')->name('tenant.documents.download');
            Route::get('documents/send_xml/{document}', 'Tenant\DocumentController@send_xml');
            Route::post('documents/email', 'Tenant\DocumentController@email');
            Route::get('documents/note/{document}', 'Tenant\NoteController@create');
            Route::get('documents/item/tables', 'Tenant\DocumentController@item_tables');
            Route::get('documents/table/{table}', 'Tenant\DocumentController@table');
            Route::get('documents/update/{document}', 'Tenant\DocumentController@update');
            Route::delete('documents/{document}', 'Tenant\DocumentController@destroy');

            //Summaries
            Route::get('summaries', 'Tenant\SummaryController@index')->name('tenant.summaries.index');
            Route::get('summaries/records', 'Tenant\SummaryController@records');
            Route::post('summaries/documents', 'Tenant\SummaryController@documents');
            Route::post('summaries', 'Tenant\SummaryController@store');
            Route::get('summaries/download/{type}/{summary}', 'Tenant\SummaryController@download')->name('tenant.summaries.download');
            Route::get('summaries/ticket/{summary}', 'Tenant\SummaryController@ticket');

            //Voided
            Route::get('voided/download/{type}/{voided}', 'Tenant\VoidedController@download')->name('tenant.voided.download');
            Route::get('voided/ticket/{voided_id}/{group_id}', 'Tenant\VoidedController@ticket');

            
            Route::get('reports', 'Tenant\ReportController@index')->name('tenant.reports.index');
            Route::post('reports/search', 'Tenant\ReportController@search')->name('tenant.search');
            Route::post('reports/pdf', 'Tenant\ReportController@pdf')->name('tenant.report_pdf');
            Route::post('reports/excel', 'Tenant\ReportController@excel')->name('tenant.report_excel');


            Route::get('options/tables', 'Tenant\OptionController@tables');
            Route::post('options/delete_documents', 'Tenant\OptionController@deleteDocuments');

app/Models/Tenant/Document.php
<?php

namespace App\Models\Tenant;

use App\Models\Tenant\Catalogs\Code;
use Hyn\Tenancy\Traits\UsesTenantConnection;
use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    use UsesTenantConnection;

    protected $with = ['customer', 'details', 'invoice', 'note'];

    protected $fillable = [
        'user_id',
        'external_id',
        'soap_type_id',
        'state_type_id',
        'ubl_version',
        'group_id',
        'document_type_code',
        'date_of_issue',
        'time_of_issue',
        'series',
        'number',
        'currency_type_code',
        'total_exportation',
        'total_taxed',
        'total_unaffected',
        'total_exonerated',
        'total_igv',
        'total_isc',
        'total_other_taxes',
        'total_other_charges',
        'total_discount',
        'total_value',
        'total',
        'establishment_id',
        'customer_id',
        'guides',
        'additional_documents',
        'legends',
        'optional',
        'filename',
        'hash',
        'qr',
        'has_xml',
        'has_pdf',
        'has_cdr'
    ];

    protected $casts = [
        'date_of_issue' => 'date',
    ];

    public function getGuidesAttribute($value)
    {
        return (object) json_decode($value);
    }

    public function setGuidesAttribute($value)
    {
        $this->attributes['guides'] = json_encode($value);
    }

    public function getAdditionalDocumentsAttribute($value)
    {
        return (object) json_decode($value);
    }

    public function setAdditionalDocumentsAttribute($value)
    {
        $this->attributes['additional_documents'] = json_encode($value);
    }

    public function getLegendsAttribute($value)
    {
        return (object) json_decode($value);
    }

    public function setLegendsAttribute($value)
    {
        $this->attributes['legends'] = json_encode($value);
    }

    public function getOptionalAttribute($value)
    {
        return (object) json_decode($value);
    }

    public function setOptionalAttribute($value)
    {
        $this->attributes['optional'] = json_encode($value);
    }

    public function getNumberFullAttribute()
    {
        return $this->series.'-'.$this->number;
    }

    public function getNumberToLetterAttribute()
    {
        $legends = $this->legends;
        $legend = collect($legends)->where('code', '1000')->first();
        return $legend->description;
    }

    public function establishment()
    {
        return $this->belongsTo(Establishment::class);
    }

    public function customer()
    {
        return $this->belongsTo(Customer::class)->with('identity_document_type');
    }

    public function soap_type()
    {
        return $this->belongsTo(SoapType::class);
    }

    public function state_type()
    {
        return $this->belongsTo(StateType::class);
    }

    public function group()
    {
        return $this->belongsTo(Group::class);
    }

    public function invoice()
    {
        return $this->hasOne(Invoice::class);
    }

    public function note()
    {
        return $this->hasOne(Note::class);
    }

    public function details()
    {
        return $this->hasMany(Detail::class);
    }

    public function logs()
    {
        return $this->hasMany(Log::class);
    }

    public function getVoidedAttribute()
    {
        if ($this->group_id === '01') {
            return Voided::whereHas('documents', function ($query) {
                                $query->where('document_id', $this->id);
                            })
                            ->whereIn('state_type_id', ['03', '05'])
                            ->first();
        }

        return Summary::whereHas('documents', function ($query) {
                            $query->where('document_id', $this->id);
                        })
                        ->whereIn('state_type_id', ['03', '05'])
                        ->where('process_type_id', 3)
                        ->first();
    }

    public function scopeWhereUser($query)
    {
        return $query->where('user_id', cache('selected_user_id'));
    }

    public function scopeWhereProcessType($query, $process_type_id)
    {
        if($process_type_id === 1) {
            return $query->where('state_type_id', '01');
        }
        return $query->where('state_type_id', '13');
    }

    public function scopeWherePeriod($query, $period, $date_start, $date_end)
    {
        if($period === 'all') {
            return $query;
        }

        return $query->whereBetween('date_of_issue', [$date_start, $date_end]);
    }

    public function getDownloadXmlAttribute()
    {
        return route('tenant.documents.download', ['type' => 'xml', 'document' => $this->id]);
    }

    public function getDownloadPdfAttribute()
    {
        return route('tenant.documents.download', ['type' => 'pdf', 'document' => $this->id]);
    }

    public function getDownloadCdrAttribute()
    {
        return route('tenant.documents.download', ['type' => 'cdr', 'document' => $this->id]);
    }

    public function getDownloadExternalXmlAttribute()
    {
        return route('tenant.documents.download_external', ['type' => 'xml', 'external_id' => $this->external_id]);
    }

    public function getDownloadExternalPdfAttribute()
    {
        return route('tenant.documents.download_external', ['type' => 'pdf', 'external_id' => $this->external_id]);
    }

    public function getDownloadExternalCdrAttribute()
    {
        return route('tenant.documents.download_external', ['type' => 'cdr', 'external_id' => $this->external_id]);
    }

    public function getDocumentTypeDescriptionAttribute()
    {
        $document_type = Code::byCatalogAndCode('01', $this->document_type_code);
        return $document_type->description;
    }
}

app/Models/Tenant/Voided.php
<?php

namespace App\Models\Tenant;

use Hyn\Tenancy\Traits\UsesTenantConnection;
use Illuminate\Database\Eloquent\Model;

class Voided extends Model
{
    use UsesTenantConnection;

    protected $table = 'voided';

    protected $fillable = [
        'user_id',
        'soap_type_id',
        'state_type_id',
        'ubl_version',
        'date_of_issue',
        'date_of_reference',
        'identifier',
        'filename',
        'has_ticket',
        'ticket',
        'has_cdr',
    ];

    protected $casts = [
        'date_of_issue' => 'date',
        'date_of_reference' => 'date',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function state_type()
    {
        return $this->belongsTo(StateType::class);
    }

    public function documents()
    {
        return $this->hasMany(VoidedDocument::class);
    }

    public function scopeWhereUser($query)
    {
        return $query->where('user_id', cache('selected_user_id'));
    }

    public function scopeWherePeriod($query, $period, $date_start, $date_end)
    {
        if($period === 'all') {
            return $query;
        }

        return $query->whereBetween('date_of_issue', [$date_start, $date_end]);
    }

    public function getDownloadCdrAttribute()
    {
        return route('tenant.voided.download', ['type' => 'cdr', 'id' => $this->id]);
    }

    public function getDownloadXmlAttribute()
    {
        return route('tenant.voided.download', ['type' => 'xml', 'id' => $this->id]);
    }


}

app/Http/Controllers/System/HomeController.php
<?php

namespace App\Http\Controllers\System;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\System\Client;

class HomeController extends Controller
{
    public function index()
    {
        $clients = Client::get();

        return view('system.dashboard')->with('clients', count($clients));
    }
}

resources/views/system/reports/index.blade.php
@extends('system.layouts.app')


@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card card-primary">
            <div class="card-header">
                   <div>
                <h4 class="card-title">Consulta de Documentos</h4>
                </div></div>
            <div class="card-body">

                @if (Session::has('form_document_list'))
                {{ Form::model(Session::get('form_document_list'), ['role' => 'form', 'autocomplete' => 'off', 'method' => 'POST']) }}
                @else
                {{ Form::open(['role' => 'form', 'autocomplete' => 'off', 'method' => 'POST']) }}
                @endif
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                {{ Form::label('document_type', 'Tipo de Documento') }}
                                {{ Form::select('document_type', ['' => 'Todos', '01'=> 'Factura', '03' => 'Boleta', '07' => 'Nota de Credito', '08' => 'Nota de Debito'], null, array('class' => 'form-control')) }}
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                {{ Form::label('serie', 'Serie') }}
                                {{ Form::text('serie', null, array('class' => 'form-control')) }}
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                {{ Form::label('number', 'Correlativo') }}
                                {{ Form::text('number', null, array('class' => 'form-control')) }}
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                {{ Form::label('total', 'Importe Total') }}
                                {{ Form::text('total', null, array('class' => 'form-control')) }}
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                {{ Form::label('state', 'Estado') }}
                                {{ Form::select('state', $states, 0, array('class' => 'form-control')) }}
                            </div>
                        </div>


                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                {{ Form::label('ruc', 'RUC Cliente') }}
                                {{ Form::text('ruc', null, array('class' => 'form-control')) }}
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="form-group">
                                {{ Form::label('client', 'Cliente') }}
                                {{ Form::text('client', null, array('class' => 'form-control')) }}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                {{ Form::label('daterange', 'Rango Fechas de Emisión') }}
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="fa fa-calendar"></i>
                                        </span>
                                    </div>
                                    {{ Form::text('daterange', null, array('class' => 'form-control pull-right')) }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <div class="box-footer">
                    {{ Form::submit('Buscar', array('class' => 'btn btn-primary'))}}
                    {{ Form::reset('Limpiar', array('class' => 'btn btn-default btn_reset'))}}
                </div>
                {{ Form::close() }}


                @if(!empty($reports) && $reports->count())
                <div class="callout callout-info">
                    <p>Se encontraron {{$reports->count()}} registros.</p>
                </div>
                <div class="box">
                    <div class="box-body table-responsive no-padding">
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th class="">#</th>
                                    <th class="">Tipo Documento</th>
                                    <th class="">Número</th>
                                    <th class="">Fecha emisión</th>
                                    <th class="">Código Externo</th>
                                    <th class="">Estado</th>
                                    <th class="">Fecha creación </th>
                                    <th class="">Descargas</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($reports as $key => $value)
                                <tr>
                                    <td>{{$value->id}}</td>
                                    <td>{{$value->document_type_code}}</td>
                                    <td>{{$value->series}}-{{$value->number}}</td>
                                    <td>{{$value->date_of_issue->format('Y-m-d')}}</td>
                                    <td>{{$value->external_id}}</td>
                                    <td>{{$value->state_type->description}}</td>
                                    <td>{{$value->created_at}}</td>
                                    <td class="">
                                        @if ($value->external_id)
                                        <div>
                                            <i class="fa fa-download"></i>
                                            <a href="{{asset($value->download_pdf)}}" class="descarga" target="_blank">PDF</a>
                                        </div>
                                        <div>
                                            <i class="fa fa-download"></i>
                                            <a href="{{asset($value->download_xml)}}" class="descarga" target="_blank">XML</a>
                                        </div>
                                            @if($value->state_type_id !== '01')
                                        <div>
                                            <i class="fa fa-download"></i>
                                            <a href="{{asset($value->download_cdr)}}" class="descarga" target="_blank">CDR</a>
                                        </div>
                                            @endif
                                        @endif
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <div class="pagination-wrapper">

                            {!! $reports->appends(['search' => Session::get('form_document_list')])->render() !!}

                        </div>
                    </div>
                </div>
                @else
                <div class="callout callout-info">
                    <p>No se encontraron registros.</p>
                </div>
                @endif

            </div>
        </div>
    </div>
</div>
@endsection


@push('scripts')

<script>

    $('.btn_reset').on('click', function (e) {
        e.preventDefault()
        reset()
    })

    function reset(){

        $('form input.form-control').val('')
        $('form select.form-control').val(0)

    }

    $('#daterange').daterangepicker({
        format: 'YYYY-MM-DD',
        autoApply: true,
        locale: {
            applyLabel: 'Aceptar',
            cancelLabel: 'Cancelar',
            fromLabel: 'Desde',
            toLabel: 'Hasta',
            daysOfWeek: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'],
            monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Setiembre', 'Octubre', 'Noviembre', 'Diciembre'],
            firstDay: 1
        }
    })

    @if(!isset(Session::get('form_document_list')['daterange']))
      $("#daterange").val('')
    @endif


</script>

@endpush