routes/web.php
            Route::delete('certificates', 'Tenant\CertificateController@destroy');

            //Establishments
            Route::get('establishments/create', 'Tenant\EstablishmentController@create');
            Route::get('establishments/tables', 'Tenant\EstablishmentController@tables');
            Route::get('establishments/record', 'Tenant\EstablishmentController@record');
            Route::post('establishments', 'Tenant\EstablishmentController@store');

            //Bank Accounts
            Route::get('bank_accounts', 'Tenant\BankAccountController@index')->name('tenant.bank_accounts.index');
            Route::get('bank_accounts/records', 'Tenant\BankAccountController@records');
            Route::get('bank_accounts/create', 'Tenant\BankAccountController@create');
            Route::get('bank_accounts/tables', 'Tenant\BankAccountController@tables');
            Route::get('bank_accounts/record/{bank_account}', 'Tenant\BankAccountController@record');
            Route::post('bank_accounts', 'Tenant\BankAccountController@store');
            Route::delete('bank_accounts/{bank_account}', 'Tenant\BankAccountController@destroy');

            //Series
            Route::get('series/records', 'Tenant\SeriesController@records');
            Route::get('series/create', 'Tenant\SeriesController@create');
            Route::get('series/tables', 'Tenant\SeriesController@tables');
            Route::post('series', 'Tenant\SeriesController@store');
            Route::delete('series/{series}', 'Tenant\SeriesController@destroy');

            //Users
            Route::get('users/create', 'Tenant\UserController@create')->name('tenant.users.create');
            Route::get('users/tables', 'Tenant\UserController@tables');
            Route::get('users/record/{user}', 'Tenant\UserController@record');
            Route::post('users', 'Tenant\UserController@store');
            Route::get('users/records', 'Tenant\UserController@records');
            Route::delete('users/{user}', 'Tenant\UserController@destroy');

            //ChargeDiscounts
            Route::get('charge_discounts', 'Tenant\ChargeDiscountController@index')->name('tenant.charge_discounts.index');
            Route::get('charge_discounts/records/{type}', 'Tenant\ChargeDiscountController@records');
            Route::get('charge_discounts/create', 'Tenant\ChargeDiscountController@create');
            Route::get('charge_discounts/tables/{type}', 'Tenant\ChargeDiscountController@tables');
            Route::get('charge_discounts/record/{charge}', 'Tenant\ChargeDiscountController@record');
            Route::post('charge_discounts', 'Tenant\ChargeDiscountController@store');
            Route::delete('charge_discounts/{charge}', 'Tenant\ChargeDiscountController@destroy');

            //Items
            Route::get('items', 'Tenant\ItemController@index')->name('tenant.items.index');
            Route::get('items/columns', 'Tenant\ItemController@columns');
            Route::get('items/records', 'Tenant\ItemController@records');
            Route::get('items/tables', 'Tenant\ItemController@tables');
            Route::get('items/record/{item}', 'Tenant\ItemController@record');
            Route::post('items', 'Tenant\ItemController@store');
            Route::delete('items/{item}', 'Tenant\ItemController@destroy');

            //Customers
            Route::get('customers', 'Tenant\CustomerController@index')->name('tenant.customers.index');
            Route::get('customers/columns', 'Tenant\CustomerController@columns');
            Route::get('customers/records', 'Tenant\CustomerController@records');
            Route::get('customers/tables', 'Tenant\CustomerController@tables');
            Route::get('customers/record/{item}', 'Tenant\CustomerController@record');
            Route::post('customers', 'Tenant\CustomerController@store');
            Route::delete('customers/{customer}', 'Tenant\CustomerController@destroy');

            //Documents
            Route::get('documents', 'Tenant\DocumentController@index')->name('tenant.documents.index');
            Route::get('documents/columns', 'Tenant\DocumentController@columns');
            Route::get('documents/records', 'Tenant\DocumentController@records');
            Route::get('documents/create', 'Tenant\DocumentController@create')->name('tenant.documents.create');
            Route::get('documents/tables', 'Tenant\DocumentController@tables');
            Route::get('documents/record/{document}', 'Tenant\DocumentController@record');
            Route::post('documents', 'Tenant\DocumentController@store');
            Route::post('documents/voided', 'Tenant\DocumentController@voided');
            Route::get('documents/to_print/{document}', 'Tenant\DocumentController@to_print');
            Route::get('documents/to_print2/{document}/{format}', 'Tenant\DocumentController@to_print2');

            Route::get('documents/download/{type}/{document}', 'Tenant\DocumentController@download')->name('tenant.documents.download');
            Route::get('documents/send_xml/{document}', 'Tenant\DocumentController@send_xml');
            Route::post('documents/email', 'Tenant\DocumentController@email');
            Route::get('documents/note/{document}', 'Tenant\NoteController@create');
            Route::get('documents/item/tables', 'Tenant\DocumentController@item_tables');
            Route::get('documents/table/{table}', 'Tenant\DocumentController@table');
            Route::get('documents/update/{document}', 'Tenant\DocumentController@update');
            Route::delete('documents/{document}', 'Tenant\DocumentController@destroy');

            //Summaries
            Route::get('summaries', 'Tenant\SummaryController@index')->name('tenant.summaries.index');
            Route::get('summaries/records', 'Tenant\SummaryController@records');
            Route::post('summaries/documents', 'Tenant\SummaryController@documents');
            Route::post('summaries', 'Tenant\SummaryController@store');
            Route::get('summaries/download/{type}/{summary}', 'Tenant\SummaryController@download')->name('tenant.summaries.download');
            Route::get('summaries/ticket/{summary}', 'Tenant\SummaryController@ticket');

            //Voided
            Route::get('voided/download/{type}/{voided}', 'Tenant\VoidedController@download')->name('tenant.voided.download');
            Route::get('voided/ticket/{voided_id}/{group_id}', 'Tenant\VoidedController@ticket');

            
            Route::get('reports', 'Tenant\ReportController@index')->name('tenant.reports.index');
            Route::post('reports/search', 'Tenant\ReportController@search')->name('tenant.search');
            Route::post('reports/pdf', 'Tenant\ReportController@pdf')->name('tenant.report_pdf');
            Route::post('reports/excel', 'Tenant\ReportController@excel')->name('tenant.report_excel');


            Route::get('options/tables', 'Tenant\OptionController@tables');
            Route::post('options/delete_documents', 'Tenant\OptionController@deleteDocuments');
            Route::post('options/delete_document_demo', 'Tenant\OptionController@deleteDocumentDemo');


            Route::get('services/ruc/{number}', 'Tenant\Api\ServiceController@ruc');
            Route::get('services/dni/{number}', 'Tenant\Api\ServiceController@dni');

            //BUSQUEDA DE DOCUMENTOS
            // Route::get('busqueda', 'Tenant\SearchController@index')->name('search');
            // Route::post('busqueda', 'Tenant\SearchController@index')->name('search');

            //Codes
            Route::get('codes/records', 'Tenant\Catalogs\CodeController@records');
            Route::get('codes/tables', 'Tenant\Catalogs\CodeController@tables');
            Route::get('codes/record/{code}', 'Tenant\Catalogs\CodeController@record');
            Route::post('codes', 'Tenant\Catalogs\CodeController@store');
            Route::delete('codes/{code}', 'Tenant\Catalogs\CodeController@destroy');

            //Units
            Route::get('unit_types/records', 'Tenant\UnitTypeController@records');
            Route::get('unit_types/record/{code}', 'Tenant\UnitTypeController@record');
            Route::post('unit_types', 'Tenant\UnitTypeController@store');
            Route::delete('unit_types/{code}', 'Tenant\UnitTypeController@destroy');

            //Banks
            Route::get('banks/records', 'Tenant\BankController@records');
            Route::get('banks/record/{bank}', 'Tenant\BankController@record');
            Route::post('banks', 'Tenant\BankController@store');
            Route::delete('banks/{bank}', 'Tenant\BankController@destroy');
        });
    });
} else {
    Route::domain(env('APP_URL_BASE'))->group(function() {

        Route::get('login', 'System\LoginController@showLoginForm')->name('login');
        Route::post('login', 'System\LoginController@login');
        Route::post('logout', 'System\LoginController@logout')->name('logout');

        Route::middleware('auth:admin')->group(function() {
            Route::get('/', function () {
                return redirect()->route('system.dashboard');
            });
            Route::get('dashboard', 'System\HomeController@index')->name('system.dashboard');

            //Clients
            Route::get('clients', 'System\ClientController@index')->name('system.clients.index');
            Route::get('clients/records', 'System\ClientController@records');
            Route::get('clients/create', 'System\ClientController@create');
            Route::post('clients', 'System\ClientController@store');
            Route::delete('clients/{client}', 'System\ClientController@destroy');
            Route::post('clients/password/{client}', 'System\ClientController@password');

            //Users
            Route::get('users/create', 'System\UserController@create')->name('system.users.create');
            Route::get('users/record', 'System\UserController@record');

app/Models/Tenant/Document.php
<?php

namespace App\Models\Tenant;

use App\Models\Tenant\Catalogs\Code;
use Hyn\Tenancy\Traits\UsesTenantConnection;
use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    use UsesTenantConnection;

    protected $with = ['customer', 'details', 'invoice', 'note'];

    protected $fillable = [
        'user_id',
        'external_id',
        'soap_type_id',
        'state_type_id',
        'ubl_version',
        'group_id',
        'document_type_code',
        'date_of_issue',
        'time_of_issue',
        'series',
        'number',
        'currency_type_code',
        'total_exportation',
        'total_taxed',
        'total_unaffected',
        'total_exonerated',
        'total_igv',
        'total_isc',
        'total_other_taxes',
        'total_other_charges',
        'total_discount',
        'total_value',
        'total',
        'establishment_id',
        'customer_id',
        'guides',
        'additional_documents',
        'legends',
        'optional',
        'filename',
        'hash',
        'qr',
        'has_xml',
        'has_pdf',
        'has_cdr'
    ];

    protected $casts = [
        'date_of_issue' => 'date',
    ];

    public function getGuidesAttribute($value)
    {
        return (object) json_decode($value);
    }

    public function setGuidesAttribute($value)
    {
        $this->attributes['guides'] = json_encode($value);
    }

    public function getAdditionalDocumentsAttribute($value)
    {
        return (object) json_decode($value);
    }

    public function setAdditionalDocumentsAttribute($value)
    {
        $this->attributes['additional_documents'] = json_encode($value);
    }

    public function getLegendsAttribute($value)
    {
        return (object) json_decode($value);
    }

    public function setLegendsAttribute($value)
    {
        $this->attributes['legends'] = json_encode($value);
    }

    public function getOptionalAttribute($value)
    {
        return (object) json_decode($value);
    }

    public function setOptionalAttribute($value)
    {
        $this->attributes['optional'] = json_encode($value);
    }

    public function getNumberFullAttribute()
    {
        return $this->series.'-'.$this->number;
    }

    public function getNumberToLetterAttribute()
    {
        $legends = $this->legends;
        $legend = collect($legends)->where('code', '1000')->first();
        return $legend->description;
    }

    public function establishment()
    {
        return $this->belongsTo(Establishment::class);
    }

    public function customer()
    {
        return $this->belongsTo(Customer::class)->with('identity_document_type');
    }

    public function soap_type()
    {
        return $this->belongsTo(SoapType::class);
    }

    public function state_type()
    {
        return $this->belongsTo(StateType::class);
    }

    public function group()
    {
        return $this->belongsTo(Group::class);
    }

    public function invoice()
    {
        return $this->hasOne(Invoice::class);
    }

    public function note()
    {
        return $this->hasOne(Note::class);
    }

    public function details()
    {
        return $this->hasMany(Detail::class);
    }

    public function logs()
    {
        return $this->hasMany(Log::class);
    }

    public function getVoidedAttribute()
    {
        if ($this->group_id === '01') {
            return Voided::whereHas('documents', function ($query) {
                                $query->where('document_id', $this->id);
                            })
                            ->whereIn('state_type_id', ['03', '05'])
                            ->first();
        }

        return Summary::whereHas('documents', function ($query) {
                            $query->where('document_id', $this->id);
                        })
                        ->whereIn('state_type_id', ['03', '05'])
                        ->where('process_type_id', 3)
                        ->first();
    }

    public function scopeWhereUser($query)
    {
        return $query->where('user_id', cache('selected_user_id'));
    }

    public function scopeWhereProcessType($query, $process_type_id)
    {
        if($process_type_id === 1) {
            return $query->where('state_type_id', '01');
        }
        return $query->where('state_type_id', '13');
    }

    public function scopeWherePeriod($query, $period, $date_start, $date_end)
    {
        if($period === 'all') {
            return $query;
        }

        return $query->whereBetween('date_of_issue', [$date_start, $date_end]);
    }

    public function getDownloadXmlAttribute()
    {
        return route('tenant.documents.download', ['type' => 'xml', 'document' => $this->id]);
    }

    public function getDownloadPdfAttribute()
    {
        return route('tenant.documents.download', ['type' => 'pdf', 'document' => $this->id]);
    }

    public function getDownloadCdrAttribute()
    {
        return route('tenant.documents.download', ['type' => 'cdr', 'document' => $this->id]);
    }

    public function getDownloadExternalXmlAttribute()
    {
        return route('tenant.documents.download_external', ['type' => 'xml', 'external_id' => $this->external_id]);
    }

    public function getDownloadExternalPdfAttribute()
    {
        return route('tenant.documents.download_external', ['type' => 'pdf', 'external_id' => $this->external_id]);
    }

    public function getDownloadExternalCdrAttribute()
    {
        return route('tenant.documents.download_external', ['type' => 'cdr', 'external_id' => $this->external_id]);
    }

    public function getDocumentTypeDescriptionAttribute()
    {
        $document_type = Code::byCatalogAndCode('01', $this->document_type_code);
        return $document_type->description;
    }
}

resources/views/tenant/templates/pdf/v21/ticket.blade.php
@php
    // $establishment = $document->establishment;
    // $customer = $document->customer;
    // $details = $document->details;
    // $document_number = $document->series.'-'.str_pad($document->number, 8, '0', STR_PAD_LEFT);
    // $document_type_description_array = [
    //     '01' => 'FACTURA',
    //     '03' => 'BOLETA DE VENTA',
    //     '07' => 'NOTA DE CREDITO',
    //     '08' => 'NOTA DE DEBITO',
    // ];
    // $identity_document_type_description_array = [
    //     '1' => 'DNI',
    //     '6' => 'RUC',
    // ];
    // $document_type_description = $document_type_description_array[$document->document_type_code];

    // $idDocument = $document->id;
    // if($note = \App\Models\Tenant\Note::where('document_id', $idDocument)->first()){
    //     $document_affected = $note->affected_document_series.'-'.$note->affected_document_number;

    //     $noteType = \App\Models\Tenant\Catalogs\Code::byCatalogAndCode('09',$note->note_type_code);
    // }
@endphp
<html>
<head>
    <title></title>
    <style type="text/css">
        @page { size: 8cm 20cm; }
        body {
            font-size: 10px;
            font-family: sans-serif;
        }
        .w-100 {
            width: 100%
        }
        .w-50 {
            width: 50%;
        }
        .text-center {
            text-align: center;
        }
        .text-right {
            text-align: right;
        }
        .py-2 {
            padding-top: 1rem;
            padding-bottom: 1rem;
        }
    </style>
</head>
<body>
    {{-- <script type="text/php">
      if (isset($pdf)) {
        $pdf->page_text(150, 60, "Para consultar el comprobante ingresar a {!! url('/') !!}/search", "Arial", 8, array(0, 0, 0));
      }
    </script> --}}
    <div class="logo">
        <img src="{{-- {{ asset('storage/uploads/logos/'.$company->logo) }} --}}" class="company_logo">
    </div>
    <div class="text-center py-2">
        <p class="text-uppercase">Nombre Comercial <br>
        Nombre <br>
        RUC: 12312312312 {{-- {{ 'RUC '.$company->number }} --}}<br>
        dirección{{-- {{ $establishment->getAddressFullAttribute() }} --}}</p>
        <p>{{-- {{ $document_type_description }} --}} <br> E L E C T R Ó N I C A</p>
    </div>
    <table class="w-100" style="border-bottom: 1px solid #bbb;">
        <tbody>
            <tr class="py-2">
                <td width="20%">
                    qwe
                </td>
                <td width="80%" class="text-right">
                    qwe
                </td>
            </tr>
            <tr>
                <td>Cliente</td>
                <td>Raul{{-- {{ $customer->name }} --}}</td>
            </tr>
            <tr>
                <td>DNI{{-- {{ $identity_document_type_description_array[$customer->identity_document_type->code] }}: --}}</td>
                <td>12346578{{-- {{ $customer->name }} --}}</td>
            </tr>
        </tbody>
    </table>
    {{-- @if($document_affected) --}}
        <table class="">
            <tbody>
                <tr>
                    <td style="vertical-align: top;" width="20%">Documento Afectado:</td>
                    <td style="vertical-align: top;"width="80%">F001-654689{{-- {{$document_affected}} --}}</td>
                </tr>
                <tr>
                    <td style="vertical-align: top;" >Tipo de nota:</td>
                    <td style="vertical-align: top;">anulacion equis{{-- {{$noteType->description}} --}}</td>
                </tr>
                <tr>
                    <td style="vertical-align: top;">Descripción:</td>
                    <td >Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua.{{-- {{$note->description}} --}}</td>
                </tr>
            </tbody>
        </table>
    {{-- @endif --}}
    <table class="w-100">
        <thead style="border-top: 1px solid #bbb; border-bottom: 1px solid #bbb;">
            <tr>
                <td style="padding: 5px 0 5px" class="text-center" width="">CANT.</td>
                <td style="padding: 5px 0 5px" width="">U.M.</td>
                <td style="padding: 5px 0 5px" width="">DESCRIPCIÓN</td>
                <td style="padding: 5px 0 5px" class="text-right" width="">P.UNIT</td>
                <td style="padding: 5px 0 5px" class="text-right" width="">TOTAL</td>
            </tr>
        </thead>
        <tbody style="border-bottom: 1px solid #bbb;">
        {{-- @foreach($details as $row) --}}
            <tr>
                <td class="text-center">1.000{{-- {!! $row->quantity !!} --}}</td>
                <td >NIU{{-- {!! $row->unit_type_code !!} --}}</td>
                <td >Chicharron{{-- {!! $row->item_description !!} --}}</td>
                <td  class="text-right" >15.50{{-- {{ number_format($row->unit_value, 2) } --}}</td>
                <td class="text-right">12.30{{-- {{ number_format($row->total, 2) }} --}}</td>
            </tr>
        </tbody>
    </table>
    <table class="w-100">
        <tbody style="border-bottom: 1px solid #bbb;">
        {{-- @endforeach --}}
            {{-- @if($document->total_exonerated > 0) --}}
                <tr>
                    <td width="80%">Operaciones Exoneradas: {{-- {{ $document->currency_type_code }} --}}</td>
                    <td width="20%" class="text-right ">0.00{{-- {{ number_format($document->total_exonerated, 2) }} --}}</td>
                </tr>
            {{-- @endif --}}
            {{-- @if($document->total_taxed > 0) --}}
                <tr>
                    <td >Operaciones Gravadas: {{-- {{ $document->currency_type_code }} --}}</td>
                    <td class="text-right ">{{-- {{ number_format($document->total_taxed, 2) }} --}}</td>
                </tr>
            {{-- @endif --}}
            <tr>
                <td >IGV: {{-- {{ $document->currency_type_code }} --}}</td>
                <td class="text-right ">{{-- {{ number_format($document->total_igv, 2) }} --}}</td>
            </tr>
            <tr>
                <td >IMPORTE TOTAL: {{-- {{ $document->currency_type_code }} --}}</td>
                <td class="text-right">{{-- {{ number_format($document->total, 2) }} --}}</td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="5" class="font-lg font-bold"  style="padding-top: 2rem;">Son: {{-- {{ $document->number_to_letter }} {{ $document->currency_type_code }} --}}</td>
            </tr>
        </tfoot>
    </table>
    <div class="text-center">
        {{-- {{ $document->hash }} --}}
        <p>Código Hash</p>
    </div>
</body>
</html>